# Generated by Django 4.0.3 on 2022-03-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30)),
                ('par', models.PositiveIntegerField(default=None)),
                ('course_record', models.PositiveIntegerField(default=None)),
                ('course_record_holder', models.CharField(default=None, max_length=40)),
                ('years_hosted_open', models.PositiveIntegerField(default=None)),
                ('previous_winners', models.CharField(default=None, max_length=200)),
                ('photos', models.CharField(default=None, max_length=200)),
            ],
        ),
    ]
