# Generated by Django 4.0.3 on 2022-03-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='photo1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='venue',
            name='photo2',
            field=models.CharField(default='', max_length=200),
        ),
    ]
