# Generated by Django 4.0.3 on 2022-03-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('venues', '0002_alter_venue_previous_winners'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='members_completed',
            field=models.ManyToManyField(related_name='venues', to='members.member'),
        ),
    ]
